"""
Django settings for otaku_stuff project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ki32x$9q__4+$t9z**z%%t(ykerx=0udshwnm)u8embju5fe1i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crud'
]

AUTH_USER_MODEL = 'crud.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'otaku_stuff.urls'

LOGIN_REDIRECT_URL = '/' # redirect in log in and sign in
LOGIN_URL = '/login/' # redirect to home if a non authenticated user tries to use the card
#LOGOUT_REDIRECT_URL = '/'

# send email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # STMP is a classic protocol to send emails
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True # cifrado seguro y puerto
EMAIL_HOST_USER = 'g2vilchis@gmail.com'
EMAIL_HOST_PASSWORD = 'aqma iaja ajtm qron' # contrasenia de aplicacion
DEFUALT_FROM_EMAIL = EMAIL_HOST_USER

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'crud.context_processors.user_logged_in',
            ],
        },
    },
]

WSGI_APPLICATION = 'otaku_stuff.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# for develop environment
SESSION_COKKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Stripe API Keys
STRIPE_PUBLIC_KEY = 'pk_test_51RIP5qB0vBm8XsikGndnz0UL593qTgV97ZZvIuA4FZkjtLRRreTZUdkr28DOBsqSaGp5lWbQf8S4tSDE84e1ohU900Db7HA6F5'
STRIPE_SECRET_KEY = 'sk_test_51RIP5qB0vBm8XsikMDXzzKJbv8b4JdwAJJExrcvlkknDVY8uuR9WILnkcvrOJEvOG22hFU8jGs69VPP1EiMaA5Zj00T9hi37My'