# Generated by Django 5.2 on 2025-04-18 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_cartitem_quantity_alter_cartitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
