# Generated by Django 5.2 on 2025-04-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_cartitem_unit_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShppingCart',
            new_name='ShopingCart',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='poduct_description',
            new_name='product_description',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
