# Generated by Django 5.2 on 2025-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_rename_shppingcart_shopingcart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetail',
            new_name='OrderDetailRelationship',
        ),
        migrations.RenameModel(
            old_name='ShopingCart',
            new_name='ShoppingCart',
        ),
        migrations.RemoveField(
            model_name='section',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='section',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(default='temporal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(default='temporal', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
