# Generated by Django 5.2 on 2025-04-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailrelationship',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
